### ISSUE TITLE
Difference in Empty Values Handling in Examples

### ISSUE THREAD

**Issue by eternalyoung** [exoego/rspec-openapi#135] opened 2023-09-08 06:57 UTC
I've encountered an issue with the gem related to how empty values are handled in generated examples. This issue seems to be platform-specific, causing inconsistencies between Linux (in my case, Ubuntu LTS 20.04) and macOS (in my case, Ventura 13.4.1) systems.

On Linux systems, when generating examples, the gem inserts a space character instead of null values. However, on macOS, it doesn't insert anything in place of empty values. As a result, when generating examples on different platforms, we get different results.

This discrepancy not only creates unnecessary changes in the Git history but also blocks merge requests due to CI checks for example generation. My repository is hosted on an Ubuntu machine, which expects spaces in empty values. However, when generating examples on macOS, these spaces are missing.

I'm using version 0.7.2 of the gem, and I haven't found a fix for this issue in the release notes. If there has been a fix for this problem in subsequent updates, please let me know.

**Comment by exoego** [comment] 2023-09-09 10:19
Thanks for reporting. 
I do not think v0.8.x addressed this.

I tried to reproduce it in https://github.com/exoego/rspec-openapi/pull/136 but could not.
It appears that specs in this repo do have such case.

Could you create a repro?

**Comment by eternalyoung** [comment] 2023-11-03 20:45
Unfortunately, I might not be able to demonstrate the repository where I noticed this issue, but here is a [repository](https://github.com/eternalyoung/openapitestrepo/tree/main) with a [generation example](https://github.com/eternalyoung/openapitestrepo/blob/main/doc/openapi.yaml#L26).
I created an [endpoint that returns a null value](https://github.com/eternalyoung/openapitestrepo/blob/main/app/controllers/example_controller.rb#L3) with[ specs on it](https://github.com/eternalyoung/openapitestrepo/blob/main/spec/openapi_spec.rb#L3-L8) and ran the schema generation.
There is no space instead of null in the schema.
<img width="380" alt="2023-11-04 в 02 43 47" src="https://github.com/exoego/rspec-openapi/assets/81143241/18218e18-afa8-438a-9837-662f07583177">

I don't have access to my Linux machine right now, but if you try to download this repo and run the generation, you'll see a space added.

**Comment by exoego** [comment] 2023-12-08 03:20
I've researched this, and the problem is caused by libyaml, which `yaml` depends on.
https://github.com/yaml/libyaml/issues/46

The good news is that the issue was already fixed in libyaml 0.2.5, which is used via Psych 3.3.2+ on Ruby 3.0+.
If you migrate to Ruby 3.0+, it will be fixed.
https://github.com/ruby/setup-ruby/issues/243#issuecomment-991323942


If you are not able to transit to Ruby 3.0+ soon, there is a workaround.
Install libyaml 0.2.5+ in your CI repo.
https://github.com/actions/runner-images/issues/6094#issuecomment-1216637809 could give a hint.


Going to close.

**Closed by exoego** 2023-12-08 03:20 UTC
Labels: need-more-info
